-- Seed the champions table with all champions

-- Cosmic champions
INSERT INTO champions (name, class) VALUES
('Adam Warlock', 'cosmic'),
('Angela', 'cosmic'),
('Captain Marvel', 'cosmic'),
('Corvus Glaive', 'cosmic'),
('Gamora', 'cosmic'),
('Gladiator', 'cosmic'),
('Gorr', 'cosmic'),
('Hyperion', 'cosmic'),
('King Groot (Deathless)', 'cosmic'),
('Knull', 'cosmic'),
('Maestro', 'cosmic'),
('Nova', 'cosmic'),
('Odin', 'cosmic'),
('Red Goblin', 'cosmic'),
('Sersi', 'cosmic'),
('Silver Surfer', 'cosmic'),
('Terrax', 'cosmic'),
('Thanos', 'cosmic'),
('The Serpent', 'cosmic'),
('Venom', 'cosmic'),
('Venom the Duck', 'cosmic'),
('Vision', 'cosmic'),
('Vox', 'cosmic'),
('Venompool', 'cosmic'),
('Superior Ironman', 'cosmic'),
('Scream', 'cosmic'),
('Carnage', 'cosmic')
ON CONFLICT (id) DO NOTHING;

-- Mutant champions
INSERT INTO champions (name, class) VALUES
('Bishop', 'mutant'),
('Colossus', 'mutant'),
('Dani Moonstar', 'mutant'),
('Deadpool', 'mutant'),
('Domino', 'mutant'),
('Dust', 'mutant'),
('Emma Frost', 'mutant'),
('Gambit', 'mutant'),
('Havok', 'mutant'),
('Namor', 'mutant'),
('Negasonic Teenage Warhead', 'mutant'),
('Nightcrawler', 'mutant'),
('Northstar', 'mutant'),
('Omega Red', 'mutant'),
('Onslaught', 'mutant'),
('Platinumpool', 'mutant'),
('Professor X', 'mutant'),
('Sauron', 'mutant'),
('Storm', 'mutant'),
('Storm X', 'mutant'),
('Stryfe', 'mutant'),
('Sunspot', 'mutant'),
('Wolverine X', 'mutant'),
('Mister Sinister', 'mutant'),
('Magneto White', 'mutant')
ON CONFLICT (id) DO NOTHING;

-- Mystic champions
INSERT INTO champions (name, class) VALUES
('America Chavez', 'mystic'),
('Diablo', 'mystic'),
('Dragon Man', 'mystic'),
('Ebony Maw', 'mystic'),
('Guillotine (Deathless)', 'mystic'),
('Juggernaut', 'mystic'),
('Kindred', 'mystic'),
('Kushala', 'mystic'),
('Longshot', 'mystic'),
('Mangog', 'mystic'),
('Mojo', 'mystic'),
('Mordo', 'mystic'),
('Sasquatch', 'mystic'),
('Scarlet Witch', 'mystic'),
('Scarlet Witch Sigil', 'mystic'),
('Sorcerer Supreme', 'mystic'),
('Symbiote Supreme', 'mystic'),
('The Destroyer', 'mystic'),
('Werewolf by Night', 'mystic'),
('White Tiger', 'mystic'),
('Wiccan', 'mystic'),
('Wong', 'mystic'),
('Enchantress', 'mystic'),
('The Hood', 'mystic'),
('Shathra', 'mystic'),
('Man-Thing', 'mystic')
ON CONFLICT (id) DO NOTHING;

-- Science champions
INSERT INTO champions (name, class) VALUES
('Ant-Man', 'science'),
('Captain America (Infinity War)', 'science'),
('Hulk', 'science'),
('Invisible Woman', 'science'),
('Joe Fixit', 'science'),
('Luke Cage', 'science'),
('Mister Negative', 'science'),
('Morbius', 'science'),
('Photon', 'science'),
('Quicksilver', 'science'),
('Sandman', 'science'),
('Silk', 'science'),
('Spider-Gwen', 'science'),
('Spider-Ham', 'science'),
('Spider-Man', 'science'),
('Spider-Man 2099', 'science'),
('Spider-Punk', 'science'),
('Spot', 'science'),
('The Overseer', 'science'),
('Thing', 'science'),
('Titania', 'science'),
('Void', 'science'),
('Hulk Immortal', 'science'),
('She-Hulk (Deathless)', 'science'),
('The Leader', 'science'),
('Count Nefaria', 'science')
ON CONFLICT (id) DO NOTHING;

-- Skill champions
INSERT INTO champions (name, class) VALUES
('Attuma', 'skill'),
('Black Cat', 'skill'),
('Black Panther', 'skill'),
('Blade', 'skill'),
('Bullseye', 'skill'),
('Chee\'ilth', 'skill'),
('Crossbones', 'skill'),
('Elsa Bloodstone', 'skill'),
('Falcon', 'skill'),
('Hawkeye', 'skill'),
('Jabari Panther', 'skill'),
('Killmonger', 'skill'),
('Korg', 'skill'),
('Mantis', 'skill'),
('Masacre', 'skill'),
('Mole Man', 'skill'),
('Moondragon', 'skill'),
('Ronin', 'skill'),
('Shang-Chi', 'skill'),
('Silver Sable', 'skill'),
('Misty Knight', 'skill'),
('Black Widow Movie', 'skill'),
('Patriot', 'skill')
ON CONFLICT (id) DO NOTHING;

-- Tech champions
INSERT INTO champions (name, class) VALUES
('Arcade', 'tech'),
('Captain America (Sam Wilson)', 'tech'),
('Civil Warrior', 'tech'),
('Guardian', 'tech'),
('Guillotine 2099', 'tech'),
('Howard the Duck', 'tech'),
('Hulkbuster', 'tech'),
('Iron Man', 'tech'),
('Iron Man (Infinity War)', 'tech'),
('Iron Man (Infamous)', 'tech'),
('Ironheart', 'tech'),
('Kang', 'tech'),
('Lady Deathstrike', 'tech'),
('Mysterio', 'tech'),
('Omega Sentinel', 'tech'),
('Peni Parker', 'tech'),
('Prowler', 'tech'),
('Red Skull', 'tech'),
('Rocket Raccoon', 'tech'),
('Shocker', 'tech'),
('Shuri', 'tech'),
('Spider-Man', 'tech'),
('Ultron', 'tech'),
('Vision (Classic)', 'tech'),
('Vision (Deathless)', 'tech'),
('War Machine', 'tech'),
('Warlock', 'tech'),
('Jack O\'Lantern', 'tech'),
('Punisher 2099', 'tech')
ON CONFLICT (id) DO NOTHING;
